<?php
declare(strict_types=1);

// Tangocard SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

TangocardUtility::setRegistrar(function (TangocardUtility $u): void {
    $u->clean = [TangocardClean::class, 'call'];
    $u->done = [TangocardDone::class, 'call'];
    $u->make_error = [TangocardMakeError::class, 'call'];
    $u->feature_add = [TangocardFeatureAdd::class, 'call'];
    $u->feature_hook = [TangocardFeatureHook::class, 'call'];
    $u->feature_init = [TangocardFeatureInit::class, 'call'];
    $u->fetcher = [TangocardFetcher::class, 'call'];
    $u->make_fetch_def = [TangocardMakeFetchDef::class, 'call'];
    $u->make_context = [TangocardMakeContext::class, 'call'];
    $u->make_options = [TangocardMakeOptions::class, 'call'];
    $u->make_request = [TangocardMakeRequest::class, 'call'];
    $u->make_response = [TangocardMakeResponse::class, 'call'];
    $u->make_result = [TangocardMakeResult::class, 'call'];
    $u->make_point = [TangocardMakePoint::class, 'call'];
    $u->make_spec = [TangocardMakeSpec::class, 'call'];
    $u->make_url = [TangocardMakeUrl::class, 'call'];
    $u->param = [TangocardParam::class, 'call'];
    $u->prepare_auth = [TangocardPrepareAuth::class, 'call'];
    $u->prepare_body = [TangocardPrepareBody::class, 'call'];
    $u->prepare_headers = [TangocardPrepareHeaders::class, 'call'];
    $u->prepare_method = [TangocardPrepareMethod::class, 'call'];
    $u->prepare_params = [TangocardPrepareParams::class, 'call'];
    $u->prepare_path = [TangocardPreparePath::class, 'call'];
    $u->prepare_query = [TangocardPrepareQuery::class, 'call'];
    $u->graphql_body = [TangocardGraphql::class, 'body'];
    $u->graphql_errors = [TangocardGraphql::class, 'errors'];
    $u->result_basic = [TangocardResultBasic::class, 'call'];
    $u->result_body = [TangocardResultBody::class, 'call'];
    $u->result_headers = [TangocardResultHeaders::class, 'call'];
    $u->transform_request = [TangocardTransformRequest::class, 'call'];
    $u->transform_response = [TangocardTransformResponse::class, 'call'];
});
